### ISSUE TITLE
Does Delete Workspace send all disk files to the graveyard?

### ISSUE THREAD

**Issue by warrenc5** [gitkraken/gk-cli-docs#7]
I have over the course of the project created multiple duplicate workspaces with repos in different disk locations.

Is it safe? Can I run it? Can I run it at 2am? Will I ever see my files again? 

I get there is the notion of a filesystem, a git repo, a gitkraken domain meta model workspace/repository and a level of indirect abstraction between all these things.

It's asking me to double/triple confirm stupidly by typing "DELETE ALL MY WORKSPACE FILES - I TAKE FULL RESPONSIBILITY FOR MY ACTIONS EVEN THOUGH I DON'T KNOW WHAT I'M DOING" 

Read the docs - but they were just as vague.. I'm tired and under pressure. The caffeine is wearing off.. Do I suck it and see? :)

Ps. pro member - but thought I'd post here rather than through support channel. Cheers.

**Comment by jkelroy** [comment]
Hello @warrenc5, in the current version, if you have repositories cloned locally, we ask if you would like to delete these as well when deleting a workspace. This may have been introduced after you submitted the issue here. If you would like to see the docs improved in a case different than the below, please let me know. 

![Image](https://github.com/user-attachments/assets/4528b601-baf7-43ec-97aa-b301c01c4773)
